### PR TITLE
[ISSUE 641] Use GraphML To Set Neuron Type

### LINKED ISSUE #641: Set neuron type (EXC or INH) from attributes in GraphML file

### PR DESCRIPTION
**Pull request by Oelgazz**
Closes #641 

There is now no longer a need for the inhibitory list xml files for the Regression Testing (soon to be applied to all other config files).

Note: This branch was pulled from the branch labeled issue 371, which is why it has extra changes.

### CODE REVIEW

**Review by jardiamj — COMMENTED** [review]
I believe that my review of #649 covers these changes.

**Comment by Oelgazz** [comment]
> I believe that my review of #649 covers these changes.

The changes in #649 should overwrite this branch.

**Review by jardiamj — APPROVED** [review]
Approving this PR as is because #649 will overwrite it. Great job Omar!

**Review by stiber — APPROVED** [review]
I approve this, but the comments about PR #649 make me a little nervous. Make sure when you merge them that, indeed, all of the desired code is there.

Also, when the dust settles, please run all of the tests manually using the testing shell scripts. Either that, or on your last PR you are ready to merge, first merge the development branch into the feature branch to trigger the automatic tests for what the result would be.

**Pull request merged**
