### PR TITLE
Issue 548 visualizer file loader

### LINKED ISSUE #548: Add file loader dialog box to Visualizer

### PR DESCRIPTION
**Pull request by whiteja2**
Closes #548

### CODE REVIEW

**Comment by stiber** [comment]
I note that there are file paths written "Windows style", using back slashes as separators. These are wrapped in calls to `os.path.normpath()`. Is that common practice in Python? In most languages, the backslash in strings is used as an escape character. Just checking before I approve.

**Comment by jardiamj** [comment]
In Linux, the backslash will be identified as an escape character therefore path strings with backslashes only work on Windows. I suggested to him, a few days ago, the use of `os.path` to make the script OS-agnostic but what I had in mind was to assemble the path like this:

```python
os.path.join('Tools','gis2graph','graph_files','King_county_NG911.graphml')
```

**Comment by whiteja2** [comment]
Based on what I found online, os.path.normpath() converts the slashes to
the appropriate form based on which operating system is being used. Through
testing, I know for certain that it can convert forward slashes to
backslashes for my Windows machine and assumed the inverse would be true. I
can go about converting all of the hardcoded paths to use forward slashes
for consistency in the code!

For the dialog box, I found os.path.normpath() to be a simpler solution as
the user passes a file path and it's then converted to the proper format
without the need for parsing the string.

**Review by stiber — APPROVED** [review]
Looks good! I think forward slashes are more likely to not cause problems or make the reader wonder.

**Comment by jardiamj** [comment]
My bad, I had only tested the previous version. @whiteja2 is correct, `os.path.normpath` does convert the path to forward slashes in Linux. After trying this new version, it does work as intended.

**Comment by stiber** [comment]
> My bad, I had only tested the previous version. @whiteja2 is correct, `os.path.normpath` does convert the path to forward slashes in Linux. After trying this new version, it does work as intended.

I was mostly concerned with the string itself. In other languages, the backslash has a special meaning when used in a string and you need `"\\"` if you want a literal backslash. So, if a forward slash will work here, then using them is preferable, as it helps code readability (by avoiding requiring the reader to either know that Python doesn't care when used in strings or requiring them to look it up).

**Pull request merged**
