### PR TITLE
Changing runtimefile location two

### PR DESCRIPTION
**Pull request by rashwini21**
Changed Runtime file locations in all files. Tested multiple small, medium , large GPU and CPU *.xml files and also tested their diffs before and after making the required changes.

Also changed the .gitignore file. In terms of changing file locations , there is need to commit the .gitignore file first and then the required changes.

There is a need for .md files in the /build/Output folder, because git will not push an empty directory to a commit.

### CODE REVIEW

**Comment by rashwini21** [comment]
Changed Runtime file locations in all files. Tested multiple small, medium , large GPU and CPU *.xml files and also tested their diffs before and after making the required changes. 

Also changed the .gitignore file. In terms of changing file locations , there is need to commit the .gitignore file first and then the required changes.

**Review by stiber — APPROVED** [review]

**Comment by stiber** [comment]
Looks good. In future, remember to set the project and link PR to associated issue(s)

**Comment by stiber** [comment]
Oh, @king-shak , once this is merges, you are go for the changes on Workbench!

**Review by king-shak — APPROVED** [review]
All looks good! I tested the changes in Workbench and everything worked.

**Comment by rashwini21** [comment]
Thankyou  @king-shak

**Pull request merged**
