### PR TITLE
[release-v0.9.3] Fixed the EventBuffer bug

### LINKED ISSUE #637: Pull together modifications from development needed to hotfix EventBuffer in master

### PR DESCRIPTION
**Pull request by stiber**
closes #637

### CODE REVIEW

**Review by KamathScience — DISMISSED** [review]

**Comment by stiber** [comment]
Here are some files to use for testing:

1. Reference outputs: [GPU-Regression-Test-GoodOutput.zip](https://github.com/user-attachments/files/15906433/GPU-Regression-Test-GoodOutput.zip)
2. Full config file: [edited_full_tR_1.0--fE_0.98_10000.xml.zip](https://github.com/user-attachments/files/15906436/edited_full_tR_1.0--fE_0.98_10000.xml.zip)

**Comment by stiber** [comment]
GPU simulation passed for all of the standard regression tests; good GPU outputs attached above. Remaining task is to run the above attached full config file for commit tagged v0.9 (as reference) and head of branch release-v0.9.3. Need to delete 3 lines from the reference output: burtinessHist (XML node that starts, 1 line of data, XML end: /Matrix).

**Comment by stiber** [comment]
I agree that that is a good patch to add here. However, I don't think that that is causing the result discrepancy, as that should only be called when an STDP simulation is run (config file specifies synapse class `AllSTDPSynapses`). The growth simulation uses dynamic spiking synapses.

**Comment by jardiamj** [comment]
After adding the fix for #675, this branch (`release-v0.9.3`) and commit tag `v0.9` produce the same output for the full growth simulation presented above.

**Comment by stiber** [comment]
@jardiamj @marinarosenwald are you in agreement that this is ready to review for release? Just a final question before I do that, since we're all asynchronous lately.

**Comment by jardiamj** [comment]
> @jardiamj @marinarosenwald are you in agreement that this is ready to review for release? Just a final question before I do that, since we're all asynchronous lately.

From my perspective, it is ready for review.

**Comment by marinarosenwald** [comment]
This looks good on my end as well.

**Review by marinarosenwald — APPROVED** [review]

**Comment by marinarosenwald** [comment]
@stiber @jardiamj PR ready for merging.

**Pull request merged**
