### PR TITLE
Encapsulate spike recording in neuro vertex classes

### PR DESCRIPTION
**Pull request by stiber**
Pull request for issue #279 

See documentation in docs/Developer/spikeRecording.md in this branch for on-the-fly notes regarding the current state of planning for this redesign. It seems like the approach to be used involves encapsulating the spike recording data structures within a new class that provides a clean interface to the recorders for their need, a clean interface to the CPU side vertex and edge classes, and the ability to allocate and copy the "raw" data structures on the GPU side.

### CODE REVIEW

**Review by kimjamesuw — APPROVED** [review]
Thanks Professor Stiber for adding all the information in spikeRecording.md!

**Comment by stiber** [comment]
> Thanks Professor Stiber for adding all the information in spikeRecording.md!

No problem. This pull request isn't ready to close yet. I don't think we can disconnect this from resolving #240; I intend this to at least be where we work together on the re-engineering. I'll do the encapsulating and perhaps what you will do is the first step in re-engineering, where you make mods to the recorder classes so that they will work with the changes.

**Comment by stiber** [comment]
Seems like we can do a relatively mild rewrite of the existing Recorder classes' `compileHistories()` methods to use the new `EventBuffer` interface. We will need to keep the `vector` of `EventBuffer`s as a public member of the `AllSpikingNeurons` class temporarily. The we can test and merge this pull request.

**Comment by jardiamj** [comment]
I looked at this to try to understand how the history of events is currently recorded. I understand that the EventBuffer will allow us to look at events that happened in past epochs. Now, we still need the variables in the struct used for the GPU code to be arrays (pointers) since those are potentially updated in GPU code. From that, I assume that when copying the data back from the GPU we would have to insert the new history into the EvenBuffer since the data types are now different.

**Comment by stiber** [comment]
And, in fact, we will always need arrays on the GPU side. Pooja and I had a great conversation on Monday. I think we're heading towards an idea where all of the things that are currently arrays on both the CPU and GPU side will become a subclass (of our own making) of `vector` on the CPU side. Then (and, Pooja, this is a new thought I've had, so it may be crazy or unworkable), the CPU side class could have methods to copy the internal data to/from the GPU (maybe also have methods to allocate/deallocate GPU storage, and maybe a data member to hold the GPU side address within the object). For the basic subclass, this would be very simple — just using the pointer to the internal array returned by `vector::data()`. For the event buffer subclassed from that, it would be more complicated (whatever we need to do, depending on the details of the two implementations).

I'd like to get closer to a situation where major simulation operations are handled by the operation manager object, and it might be the case that the above would allow us to have top-level operations to command copying data to/from the GPU and such copying would happen everywhere via these objects. Not sure about this yet. But we definitely want something like this (copy everything from GPU to CPU) command capability at the very end of the simulation, if we want to be able to guarantee the ability to completely serialize out the state of the simulation. Come to think of it, that would also require commanding a copy of everything from CPU to GPU at the start of a simulation, if we deserialize.

Regardless, baby steps first.

**Comment by PoojaPal2021** [comment]
The changes in the commits from this pull request are accommodated in #334.
Conversation at this pull request might be useful later

**Pull request closed without merging**
